# Autogenerated wrapper script for procps_jll for aarch64-linux-gnu
export free, hugetop, libproc2, pgrep, pidof, pkill, pmap, ps, pskill, pwdx, slabtop, sysctl, tload, top, uptime, vmstat, w, watch

using Ncurses_jll
JLLWrappers.@generate_wrapper_header("procps")
JLLWrappers.@declare_library_product(libproc2, "libproc2.so.1")
JLLWrappers.@declare_executable_product(free)
JLLWrappers.@declare_executable_product(hugetop)
JLLWrappers.@declare_executable_product(pgrep)
JLLWrappers.@declare_executable_product(pidof)
JLLWrappers.@declare_executable_product(pkill)
JLLWrappers.@declare_executable_product(pmap)
JLLWrappers.@declare_executable_product(ps)
JLLWrappers.@declare_executable_product(pskill)
JLLWrappers.@declare_executable_product(pwdx)
JLLWrappers.@declare_executable_product(slabtop)
JLLWrappers.@declare_executable_product(sysctl)
JLLWrappers.@declare_executable_product(tload)
JLLWrappers.@declare_executable_product(top)
JLLWrappers.@declare_executable_product(uptime)
JLLWrappers.@declare_executable_product(vmstat)
JLLWrappers.@declare_executable_product(w)
JLLWrappers.@declare_executable_product(watch)
function __init__()
    JLLWrappers.@generate_init_header(Ncurses_jll)
    JLLWrappers.@init_library_product(
        libproc2,
        "lib/libproc2.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_executable_product(
        free,
        "bin/free",
    )

    JLLWrappers.@init_executable_product(
        hugetop,
        "bin/hugetop",
    )

    JLLWrappers.@init_executable_product(
        pgrep,
        "bin/pgrep",
    )

    JLLWrappers.@init_executable_product(
        pidof,
        "bin/pidof",
    )

    JLLWrappers.@init_executable_product(
        pkill,
        "bin/pkill",
    )

    JLLWrappers.@init_executable_product(
        pmap,
        "bin/pmap",
    )

    JLLWrappers.@init_executable_product(
        ps,
        "bin/ps",
    )

    JLLWrappers.@init_executable_product(
        pskill,
        "bin/kill",
    )

    JLLWrappers.@init_executable_product(
        pwdx,
        "bin/pwdx",
    )

    JLLWrappers.@init_executable_product(
        slabtop,
        "bin/slabtop",
    )

    JLLWrappers.@init_executable_product(
        sysctl,
        "sbin/sysctl",
    )

    JLLWrappers.@init_executable_product(
        tload,
        "bin/tload",
    )

    JLLWrappers.@init_executable_product(
        top,
        "bin/top",
    )

    JLLWrappers.@init_executable_product(
        uptime,
        "bin/uptime",
    )

    JLLWrappers.@init_executable_product(
        vmstat,
        "bin/vmstat",
    )

    JLLWrappers.@init_executable_product(
        w,
        "bin/w",
    )

    JLLWrappers.@init_executable_product(
        watch,
        "bin/watch",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
